ErrorCode = {
  API_SUCCESS: 0,
  JWT_EXPIRED: 1000,
  OBJECT_SAVE_FAILED: 1001,
  USERNAME_ALREADY_EXISTS: 1002,
  EMAIL_ALREADY_EXISTS: 1003,
  OTHER_ERROR: 1004,

  USER_NAME_INVALID: 1005,
  USER_PASSWORD_INVALID: 1006,
  USER_ROLE_INVALID: 1007,
  EMAIL_INVALID: 1008,
  USER_GENDER_INVALID: 1009,
  USER_NOT_EXISTS: 1010,
  USER_NAME_OR_PASSWORD_INVALID: 1011,
  TYPE_USER_INVALID: 1012,
  USER_COMPANY_INVALID: 1013,
  PERMISSION_DENIED: 1014,
  PROJECT_TITLE_INVALID: 1015,
  COUNTRY_INVALID: 1016,
  CATEGORY_INVALID: 1017,
  CATEGORY_ALREADY_EXISTS: 1018,
  CATEGORY_DOES_NOT_EXISTS: 1019,
  COUNTRY_ALREADY_EXISTS: 1020,
  COUNTRY_DOES_NOT_EXISTS: 1021,
  PROJECT_DOES_NOT_EXISTS: 1022,
  MISSING_MONEY_DONATE: 1023,
  MISSING_PERCENT_DONATE: 1024,
  PERCENT_DONATE_INVALID: 1025,
  MISSING_USER_DONATE: 1026,
  
  
  AUTHENTICATE: 1999,
}

ErrorMessage = {
  [ErrorCode.API_SUCCESS]: 'API success.',
  [ErrorCode.JWT_EXPIRED]: 'Session token expired.',
  [ErrorCode.OBJECT_SAVE_FAILED]: 'Failed while save object',
  [ErrorCode.USERNAME_ALREADY_EXISTS]: 'username is already exists',
  [ErrorCode.USER_PASSWORD_INVALID]: 'password invalid',
  [ErrorCode.USER_NAME_INVALID]: 'usename invalid',
  [ErrorCode.USER_ROLE_INVALID]: 'user`s role invalid',
  [ErrorCode.EMAIL_INVALID]: 'email invalid',
  [ErrorCode.EMAIL_ALREADY_EXISTS]: 'email is already exists',
  [ErrorCode.USER_GENDER_INVALID]: 'user`s gender invalid',
  [ErrorCode.AUTHENTICATE]: 'uauthenticate failed',
  [ErrorCode.USER_NOT_EXISTS]: 'user`s account not exists',
  [ErrorCode.USER_NAME_OR_PASSWORD_INVALID]: 'username or password invalid',
  [ErrorCode.TYPE_USER_INVALID]: 'type of user invalid',
  [ErrorCode.USER_COMPANY_INVALID]: 'company do not blank',
  [ErrorCode.PERMISSION_DENIED]: 'permission denied',
  [ErrorCode.PROJECT_TITLE_INVALID]: 'title do not blank',
  [ErrorCode.COUNTRY_INVALID]: 'country invalid',
  [ErrorCode.CATEGORY_INVALID]: 'category invalid',
  [ErrorCode.CATEGORY_ALREADY_EXISTS]: 'category is already exists',
  [ErrorCode.COUNTRY_ALREADY_EXISTS]: 'country is already exists',
  [ErrorCode.CATEGORY_DOES_NOT_EXISTS]: 'category does not exists',
  [ErrorCode.COUNTRY_DOES_NOT_EXISTS]: 'country does not exists',
  [ErrorCode.PROJECT_DOES_NOT_EXISTS]: 'project does not exists',
  [ErrorCode.MISSING_MONEY_DONATE]: 'missing money to donate',
  [ErrorCode.MISSING_PERCENT_DONATE]: 'missing percent to donate',
  [ErrorCode.PERCENT_DONATE_INVALID]: 'percent donate invalid',
  [ErrorCode.MISSING_USER_DONATE]: 'missing user donate',
};
